# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: download-pv
#   labels:
#     type: downloads
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: local-storage
#   local:
#     path: "/home/downloader/downloads"
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - kind-control-plane
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: storage-pv
#   labels:
#     type: storage
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: local-storage
#   local:
#     path: "/home/downloader/storage"
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - kind-control-plane
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: zookeeper-data-pv
#   labels:
#     type: zookeeper-data
# spec:
#   storageClassName: "standard"
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/data/zookeeper/data" 
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: zookeeper-logs-pv
#   labels:
#     type: zookeeper-logs
# spec:
#   storageClassName: "standard"
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/data/zookeeper/logs" 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-logs-pv
  labels:
    type: zookeeper-logs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: "/data/zookeeper/logs" 
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: zookeeper-data-pv
#   labels:
#     type: zookeeper-data
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: local-storage
#   local:
#     path: "/data/zookeeper/data" 
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - kind-control-plane
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: kafka-data-pv
#   labels:
#     type: kafka-data
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: local-storage
#   local:
#     path: "/home/downloader/kafka/data" 
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - kind-control-plane

